### ISSUE TITLE
Recieve mails like mutt

### ISSUE THREAD

**Issue by ttxtea** [lalor/emcli#1]
This is a wonderfull idea! A terminal email client in python. Mutt of course has many features, but even forwarding emails with attachment is difficult in mutt. Mutt even neomutt is difficult to contribute to or even install due to its dependencies. A "pymutt" would be great, since it might be easier to programm and add features an plugins. Is there a plan to add email reading functionality and a small terminal gui?

**Comment by lalor** [comment]
Thank you for your attention about this little project. There is no plan to support reading functionality because reading in terminal is not convenient.
